name: katro_timeline
description: "Flutter time line 2024"
version: 1.0.0

homepage: https://github.com/mohammedjmosalam/flutter_time_line

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

